### ISSUE TITLE
상품 DB 게시판 구현

### ISSUE THREAD

**Issue by rlouol** [sojlee/SEproj3#16]
프로젝트2때 구현했던 간단한 게시판을 이용하여 구현시작

**Comment by rlouol** [comment]
CSS적용 완료, 상품DB로 넘어가는 로직 작성

**Comment by sojlee** [comment]
js에서 DB 배열 쪼개서 넣기, html파일에서 데이터 보이게 하기 수정

**Comment by sojlee** [comment]
update page구현 중 static 이미지 로드 안됨 문제 발생

**Comment by sojlee** [comment]
update page static 파일 로드 문제 해결, /productDB/update/:idx와 뷰 설정 완료

**Comment by sojlee** [comment]
update 페이지 수정 완료

**Comment by sojlee** [comment]
update 페이지 수정버튼 추가, 숫자만 입력받게 추가

**Comment by sojlee** [comment]
update date 보기 방식 변경, update 시 update date 변경되게 수정

**Comment by sojlee** [comment]
다중 상품 이미지 업로드 기능 구현

**Comment by sojlee** [comment]
DB에 default img 설정하여 이미지 추가 안하면 상품이미지를 볼 수 없게 수정

**Comment by sojlee** [comment]
상품 추가 기능 구현

**Comment by sojlee** [comment]
상품 이미지 url 저장 방식 변경

**Comment by sojlee** [comment]
상품 삭제 기능 구현
