### ISSUE TITLE
구매 목록 페이지 보기 구현

### ISSUE THREAD

**Issue by sojlee** [sojlee/SEproj3#35]
구매 목록 페이지 보기 구현

**Comment by rlouol** [comment]
cart.html에서 복사하여 buy.html로 생성

**Comment by rlouol** [comment]
order_list에서 customer 컬럼이 해당 유저와 동일한 데이터들을 가져온다.

**Comment by rlouol** [comment]
ship값의 의미
0 : 배송준비중
1 : 배송완료

**Comment by rlouol** [comment]
프로토타입 작성 완료

**Comment by rlouol** [comment]
구매목록 페이지 name : buy

**Comment by sojlee** [comment]
사용자가 구매한 목록을 볼 수 있는 페이지. 구현 완료
