### ISSUE TITLE
상품페이지 레이아웃 제작 시작

### ISSUE THREAD

**Issue by rlouol** [sojlee/SEproj3#8]
body 최상단의 서브배너 제거

**Comment by rlouol** [comment]
Search bar 제거, 상품 이름, 각종 정보의 프로토타입 작성

**Comment by rlouol** [comment]
이미지 슬라이더 제거, , 컬러 선택 기능 제거

**Comment by rlouol** [comment]
![image](https://user-images.githubusercontent.com/56918200/84344017-a0fc3d80-abe4-11ea-8408-2da79c9de287.png)
![image](https://user-images.githubusercontent.com/56918200/84344045-b40f0d80-abe4-11ea-92d7-6259f1fe960a.png)
![image](https://user-images.githubusercontent.com/56918200/84344069-c12bfc80-abe4-11ea-9048-d63ed2c0cb0a.png)

**Comment by rlouol** [comment]
밑 부분은 남겨둠

**Comment by rlouol** [comment]
1차적인 틀 작성 완료

**Comment by sojlee** [comment]
상품 페이지 UI 수정

**Comment by sojlee** [comment]
상품 페이지 DB와 연결해 상품 목록 볼 수 있게 수정

**Comment by sojlee** [comment]
상품 상세 보기 페이지 기능 구현 완료
